# Importing Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

genomic_data = pd.read_csv("genomic_data.csv")
genomic_data.head()

,SNP_A,SNP_B,SSR_B,InDel_C,Non-N_bases,Disease_resistance
0,63551.52083,49064.67712,0.791944,0.700105,1.697098e+07,1
1,77360.71741,82286.81238,0.551061,0.281225,5.202259e+06,1
2,68029.36021,70677.51691,1.126331,0.030957,1.821082e+07,0
3,63225.30419,89519.66558,1.725027,0.428687,1.675132e+07,0
4,53163.34835,41358.61485,1.270834,0.162112,1.566956e+07,1

In [2]:
genomic_data.describe()

,SNP_A,SNP_B,SSR_B,InDel_C,Non-N_bases,Disease_resistance
count,16519.000000,16519.000000,16519.000000,16519.000000,1.651900e+04,16519.000000
mean,59049.942007,95486.377616,1.149135,0.404939,1.100673e+07,0.490405
std,24029.569536,35074.351613,0.489767,0.227734,5.218024e+06,0.499923
min,18006.013320,35027.900820,0.300340,0.010072,2.001058e+06,0.000000
25%,38326.874755,64916.458870,0.722776,0.206395,6.434717e+06,0.000000
50%,58715.571550,95876.747080,1.150954,0.405787,1.097983e+07,0.000000
75%,79976.603935,125858.587750,1.573706,0.602038,1.551757e+07,1.000000
max,100998.170000,155990.168100,1.999946,0.799959,1.999927e+07,1.000000

In [3]:
genomic_data.dtypes

SNP_A                 float64
SNP_B                 float64
SSR_B                 float64
InDel_C               float64
Non-N_bases           float64
Disease_resistance      int64
dtype: object

In [4]:
genomic_data.isna().sum()

SNP_A                 0
SNP_B                 0
SSR_B                 0
InDel_C               0
Non-N_bases           0
Disease_resistance    0
dtype: int64

# Splitting the dataset

In [5]:
X = genomic_data[["SNP_A","SNP_B","SSR_B","InDel_C","Non-N_bases"]]
y = genomic_data['Disease_resistance']

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Training the model

In [7]:
model = RandomForestClassifier()
model.fit(X_train, y_train)

RandomForestClassifier()

In [8]:
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy of the model: {accuracy * 100}%")

Accuracy of the model: 50.0%

In [9]:
class_report = classification_report(y_test, y_pred)
print("Classification Report:")
print(class_report)

Classification Report:
              precision    recall  f1-score   support

           0       0.52      0.55      0.53      1733
           1       0.47      0.45      0.46      1571

    accuracy                           0.50      3304
   macro avg       0.50      0.50      0.50      3304
weighted avg       0.50      0.50      0.50      3304