In [3]:
!pip install pgmpy

Requirement already satisfied: pgmpy in c:\users\renus\anaconda3\anaconda\lib\site-packages (1.0.0)
Requirement already satisfied: networkx in c:\users\renus\anaconda3\anaconda\lib\site-packages (from pgmpy) (3.4.2)
Requirement already satisfied: numpy in c:\users\renus\anaconda3\anaconda\lib\site-packages (from pgmpy) (2.1.3)
Requirement already satisfied: scipy in c:\users\renus\anaconda3\anaconda\lib\site-packages (from pgmpy) (1.15.3)
Requirement already satisfied: scikit-learn in c:\users\renus\anaconda3\anaconda\lib\site-packages (from pgmpy) (1.6.1)
Requirement already satisfied: pandas in c:\users\renus\anaconda3\anaconda\lib\site-packages (from pgmpy) (2.2.3)
Requirement already satisfied: torch in c:\users\renus\anaconda3\anaconda\lib\site-packages (from pgmpy) (2.9.0)
Requirement already satisfied: statsmodels in c:\users\renus\anaconda3\anaconda\lib\site-packages (from pgmpy) (0.14.4)
Requirement already satisfied: tqdm in c:\users\renus\anaconda3\anaconda\lib\site-packages (from pgmpy) (4.67.1)
Requirement already satisfied: joblib in c:\users\renus\anaconda3\anaconda\lib\site-packages (from pgmpy) (1.4.2)
Requirement already satisfied: opt-einsum in c:\users\renus\anaconda3\anaconda\lib\site-packages (from pgmpy) (3.4.0)
Requirement already satisfied: pyro-ppl in c:\users\renus\anaconda3\anaconda\lib\site-packages (from pgmpy) (1.9.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\renus\anaconda3\anaconda\lib\site-packages (from pandas->pgmpy) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\renus\anaconda3\anaconda\lib\site-packages (from pandas->pgmpy) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\renus\anaconda3\anaconda\lib\site-packages (from pandas->pgmpy) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\renus\anaconda3\anaconda\lib\site-packages (from python-dateutil>=2.8.2->pandas->pgmpy) (1.17.0)
Requirement already satisfied: pyro-api>=0.1.1 in c:\users\renus\anaconda3\anaconda\lib\site-packages (from pyro-ppl->pgmpy) (0.1.2)
Requirement already satisfied: filelock in c:\users\renus\anaconda3\anaconda\lib\site-packages (from torch->pgmpy) (3.17.0)
Requirement already satisfied: typing-extensions>=4.10.0 in c:\users\renus\anaconda3\anaconda\lib\site-packages (from torch->pgmpy) (4.12.2)
Requirement already satisfied: sympy>=1.13.3 in c:\users\renus\anaconda3\anaconda\lib\site-packages (from torch->pgmpy) (1.13.3)
Requirement already satisfied: jinja2 in c:\users\renus\anaconda3\anaconda\lib\site-packages (from torch->pgmpy) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in c:\users\renus\anaconda3\anaconda\lib\site-packages (from torch->pgmpy) (2025.3.2)
Requirement already satisfied: setuptools in c:\users\renus\anaconda3\anaconda\lib\site-packages (from torch->pgmpy) (72.1.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\renus\anaconda3\anaconda\lib\site-packages (from sympy>=1.13.3->torch->pgmpy) (1.3.0)
Requirement already satisfied: colorama in c:\users\renus\anaconda3\anaconda\lib\site-packages (from tqdm->pgmpy) (0.4.6)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\renus\anaconda3\anaconda\lib\site-packages (from jinja2->torch->pgmpy) (3.0.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\renus\anaconda3\anaconda\lib\site-packages (from scikit-learn->pgmpy) (3.5.0)
Requirement already satisfied: patsy>=0.5.6 in c:\users\renus\anaconda3\anaconda\lib\site-packages (from statsmodels->pgmpy) (1.0.1)
Requirement already satisfied: packaging>=21.3 in c:\users\renus\anaconda3\anaconda\lib\site-packages (from statsmodels->pgmpy) (24.2)

In [12]:
import pandas as pd
from pgmpy.models import DiscreteBayesianNetwork
from pgmpy.estimators import ParameterEstimator, BayesianEstimator
from pgmpy.estimators import MaximumLikelihoodEstimator
from pgmpy.inference import VariableElimination

In [13]:
data = pd.read_csv('heart_cleveland_upload.csv')

In [14]:
data.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,condition
0,69,1,0,160,234,1,2,131,0,0.1,1,1,0,0
1,69,0,0,140,239,0,0,151,0,1.8,0,2,0,0
2,66,0,0,150,226,0,0,114,0,2.6,2,0,0,0
3,65,1,0,138,282,1,2,174,0,1.4,1,1,0,1
4,64,1,0,110,211,0,2,144,1,1.8,1,0,0,0

In [15]:
data.tail()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,condition
292,40,1,3,152,223,0,0,181,0,0.0,0,0,2,1
293,39,1,3,118,219,0,0,140,0,1.2,1,0,2,1
294,35,1,3,120,198,0,0,130,1,1.6,1,0,2,1
295,35,0,3,138,183,0,0,182,0,1.4,0,0,0,0
296,35,1,3,126,282,0,2,156,1,0.0,0,0,2,1

In [16]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 297 entries, 0 to 296
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        297 non-null    int64
 1   sex        297 non-null    int64
 2   cp         297 non-null    int64
 3   trestbps   297 non-null    int64
 4   chol       297 non-null    int64
 5   fbs        297 non-null    int64
 6   restecg    297 non-null    int64
 7   thalach    297 non-null    int64
 8   exang      297 non-null    int64
 9   oldpeak    297 non-null    float64
 10  slope      297 non-null    int64
 11  ca         297 non-null    int64
 12  thal       297 non-null    int64
 13  condition  297 non-null    int64
dtypes: float64(1), int64(13)
memory usage: 32.6 KB

In [17]:
data.describe()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,condition
count,297.000000,297.000000,297.000000,297.000000,297.000000,297.000000,297.000000,297.000000,297.000000,297.000000,297.000000,297.000000,297.000000,297.000000
mean,54.542088,0.676768,2.158249,131.693603,247.350168,0.144781,0.996633,149.599327,0.326599,1.055556,0.602694,0.676768,0.835017,0.461279
std,9.049736,0.468500,0.964859,17.762806,51.997583,0.352474,0.994914,22.941562,0.469761,1.166123,0.618187,0.938965,0.956690,0.499340
min,29.000000,0.000000,0.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,48.000000,0.000000,2.000000,120.000000,211.000000,0.000000,0.000000,133.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,56.000000,1.000000,2.000000,130.000000,243.000000,0.000000,1.000000,153.000000,0.000000,0.800000,1.000000,0.000000,0.000000,0.000000
75%,61.000000,1.000000,3.000000,140.000000,276.000000,0.000000,2.000000,166.000000,1.000000,1.600000,1.000000,1.000000,2.000000,1.000000
max,77.000000,1.000000,3.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,2.000000,3.000000,2.000000,1.000000

In [18]:
model = DiscreteBayesianNetwork([('age', 'condition'),
('sex', 'condition'),
('cp', 'condition'),
('trestbps', 'condition'),
('chol', 'condition')])

In [19]:
model.fit(data,estimator=MaximumLikelihoodEstimator)

INFO:pgmpy: Datatype (N=numerical, C=Categorical Unordered, O=Categorical Ordered) inferred from data:
 {'age': 'N', 'sex': 'N', 'cp': 'N', 'trestbps': 'N', 'chol': 'N', 'fbs': 'N', 'restecg': 'N', 'thalach': 'N', 'exang': 'N', 'oldpeak': 'N', 'slope': 'N', 'ca': 'N', 'thal': 'N', 'condition': 'N'}

In [20]:
HeartDiseasetest_infer = VariableElimination(model)

In [21]:
q1=HeartDiseasetest_infer.query(variables=['condition'],evidence={'cp':3})
print(q1)

+--------------+------------------+
| condition    |   phi(condition) |
+==============+==================+
| condition(0) |           0.4997 |
+--------------+------------------+
| condition(1) |           0.5003 |
+--------------+------------------+

In [25]:
q2=HeartDiseasetest_infer.query(variables=['condition'],evidence={'trestbps':100})
print(q2)

+--------------+------------------+
| condition    |   phi(condition) |
+==============+==================+
| condition(0) |           0.4998 |
+--------------+------------------+
| condition(1) |           0.5002 |
+--------------+------------------+

In [27]:
q3=HeartDiseasetest_infer.query(variables=['condition'],evidence={'age':50})
print(q3)

+--------------+------------------+
| condition    |   phi(condition) |
+==============+==================+
| condition(0) |           0.4999 |
+--------------+------------------+
| condition(1) |           0.5001 |
+--------------+------------------+

In [28]:
q4=HeartDiseasetest_infer.query(variables=['condition'],evidence={'chol':220})
print(q4)

+--------------+------------------+
| condition    |   phi(condition) |
+==============+==================+
| condition(0) |           0.5003 |
+--------------+------------------+
| condition(1) |           0.4997 |
+--------------+------------------+